Initial abstractions
vostok/servicediscovery.telemetry pull request #1
Opened 2021-10-19 06:50 UTC by Jevvry

2021-10-20 13:03 UTC, TGladysheva commented on Vostok.ServiceDiscovery.Telemetry/Event/ServiceDiscoveryEventKind.cs
> +        ReplicaStart = 2,
Я бы ReplicaStart и ReplicaStop в начало списка перенесла

2021-10-20 13:25 UTC, TGladysheva commented on Vostok.ServiceDiscovery.Telemetry/ServiceDiscoveryContext.cs
> +        private static readonly AsyncLocal<IServiceDiscoveryEventsBuilder> Container = new AsyncLocal<IServiceDiscoveryEventsBuilder>();
Есть ощущение, что весь билдер тут не нужен. 
Как будто бы мы этот контекст будем использовать из SDManagerExtersions. А там у нас не будет EventKind'а и свойств кто-когда-почему добавил реплику в блеклист.

Более того, заполнять часть этих свойств мы будем непосредственно из мониторинга SD, т.к. в методы SDManager его не прокинуть. Это, кажется, не ответственность мониторинга, знать, как создавать SDEvent'ы.

Можно создать класс попроще, с ограниченным набором свойств

2021-10-21 13:44 UTC, kungasc commented on Vostok.ServiceDiscovery.Telemetry/Event/ServiceDiscoveryEvent.cs
> +            [NotNull] string environment = "default",
вместо опциональных параметров надо использовать сетер

public string Environment { get; set; } = "default"

но вообще вроде бы никакого дефолта "default" в либах SD нету, и этой либе он не нужен

2021-10-21 13:49 UTC, kungasc commented on Vostok.ServiceDiscovery.Telemetry/EventBuilder/ServiceDiscoveryEventsBuilder.cs
> +    public class ServiceDiscoveryEventsBuilder: IServiceDiscoveryEventsBuilder
а зачем этот билдер, у вас правда эвент по кусочкам собирать нужно, а не просто создать и записать?

аналогично с ServiceDiscoveryContext

2021-10-21 13:53 UTC, kungasc commented on Vostok.ServiceDiscovery.Telemetry/ServiceDiscoveryContext.cs
> +    public static class ServiceDiscoveryContext
не знаю, что делает этот класс (даже доки нету), но предположу что название не соответствует действительности

если он только про отправку эвентов, а не про что-то общее из мира ServiceDiscovery

2021-10-21 14:10 UTC, TGladysheva commented on Vostok.ServiceDiscovery.Telemetry/EventBuilder/ServiceDiscoveryEventsBuilder.cs
> +    public class ServiceDiscoveryEventsBuilder: IServiceDiscoveryEventsBuilder
>а зачем этот билдер, у вас правда эвент по кусочкам собирать нужно, а не просто создать и записать?


Да, правда

2021-10-21 14:11 UTC, TGladysheva commented on Vostok.ServiceDiscovery.Telemetry/ServiceDiscoveryContext.cs
> +    public static class ServiceDiscoveryContext
Да, мы обсудили, что в его названии должно быть слово Event или Operation

2021-11-14 14:04 UTC, TGladysheva commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/ServiceDiscoveryEventDescription.cs
> +        public ServiceDiscoveryEventDescription AddProperties(params (string key, string value)[] properties) =>
Я бы сделала метод, который просто key value принимает, а не массив.

2021-11-14 14:05 UTC, TGladysheva commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/ServiceDiscoveryEventDescription.cs
> +        public ServiceDiscoveryEventDescription AddProperties(params (string key, string value)[] properties) =>
Все равно у нас на разных уровнях вложенности это может заполняться.

2021-11-14 14:07 UTC, TGladysheva commented on Vostok.ServiceDiscovery.Telemetry/ServiceDiscoveryEventKeys.cs
> +        public const string EventCreatorId = "userId";
Слово Event можно убрать из названия полей, оно есть в названии класса

2021-11-14 14:22 UTC, TGladysheva commented on Vostok.ServiceDiscovery.Telemetry/Event/ServiceDiscoveryEvent.cs
> +            ServiceDiscoveryEventKind eventKind,
Может eventKind первым аргументом?

2021-11-23 11:20 UTC, TGladysheva commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/ServiceDiscoveryEventDescription.cs
> +        private IDisposable descriptionScope;
ISDEventDescription лучше, а не IDisposable

2021-11-25 06:55 UTC, Jevvry commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/ServiceDiscoveryEventDescription.cs
> +        private IDisposable descriptionScope;
Scope задается вот в этой [части](https://github.com/vostok/servicediscovery.telemetry/blob/initial_models/Vostok.ServiceDiscovery.Telemetry/ServiceDiscoveryEventDescriptionContext.cs#L33) и он как раз хранит в себе логику замены на прежний `IServiceDiscoveryEventDescription` при диспоузе текущего. Нам ведь не нужны методы `IServiceDiscoveryEventDescription` для скоупа.

2021-11-25 09:34 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/Event/ServiceDiscoveryEventKind.cs
> +        ReplicaStart = 0,
ReplicaStart vs AddToBlackList

вроде как все эвенты про реплику, поэтому хватит и просто Start/Stop

либо везде с Replica (ReplicaAddedToBlacklist)

2021-11-25 12:18 UTC, Jevvry commented on Vostok.ServiceDiscovery.Telemetry/Event/ServiceDiscoveryEventKind.cs
> +        ReplicaStart = 0,
Лучше везде реплику дописать

2021-11-28 09:54 UTC, KungA requested changes

2021-11-28 09:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventSender/IServiceDiscoveryEventSender.cs
> +        void Send([NotNull] ServiceDiscoveryEvent serviceDiscoveryEvent);
```suggestion
        void Send([NotNull] ServiceDiscoveryEvent event);
```

2021-11-28 09:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/Extensions/IServiceDiscoveryEventDescriptionExtensions.cs
> +    public static class IServiceDiscoveryEventDescriptionExtensions
экстеншены лучше держать в той же папке, что и соответствующая модель

2021-11-28 09:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/Extensions/IServiceDiscoveryEventDescriptionExtensions.cs
> +            serviceDiscoveryEventDescription.AddProperty(ServiceDiscoveryWellKnownProperties.CreatorId, userId);
поля разъехались как будто (creatorId vs userId)

лучше везде одинаково назвать

2021-11-28 09:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/ServiceDiscoveryEventDescription.cs
> +    internal class ServiceDiscoveryEventDescription : IServiceDiscoveryEventDescription
по сути это и есть ServiceDiscoveryEventsBuilder

не понятно, зачем два отдельных класса, лучше этот переименовать в билдер и сделать ему поле CurrentEvents (см ISpanBuilder)

2021-11-28 09:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/IServiceDiscoveryEventDescription.cs
> +        IReadOnlyList<string> Replicas { get; }
а зачем столько публичных полей торчит кусочных?

как будто ни одно в итоге пользователю и не нужно

2021-11-28 09:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/IServiceDiscoveryEventDescription.cs
> +        IServiceDiscoveryEventDescription AddProperty([NotNull] string key, [NotNull] string value);
```suggestion
        IServiceDiscoveryEventDescription SetProperty([NotNull] string key, [NotNull] string value);
```

2021-11-28 09:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/ServiceDiscoveryEventBuilder.cs
> +                DateTimeOffset.UtcNow,
```suggestion
                DateTimeOffset.Now,
```

2021-11-28 09:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/ServiceDiscoveryEventBuilder.cs
> +                DateTimeOffset.UtcNow,
иначе нет смысла от оффсета

2021-11-28 09:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/ServiceDiscoveryEventBuilder.cs
> +                DateTimeOffset.UtcNow,
логичней кажется таймстемп заполнять при создании эвента, а в билде

2021-11-28 09:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/ServiceDiscoveryEventDescription.cs
> +        public ServiceDiscoveryEventDescription(IServiceDiscoveryEventDescription eventDescription)
``
```suggestion
        public ServiceDiscoveryEventDescription Clone()
```

2021-11-28 09:57 UTC, KungA commented
А ещё не хватает документаций на всех публичных методах/модельках.

И там же примеров использований (см ISpanBuilder).

2021-11-28 09:59 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/ServiceDiscoveryEventDescription.cs
> +        private IDisposable descriptionScope;
тут всё ок, IDisposable контекста

2021-11-28 10:00 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/ServiceDiscoveryEventDescriptionContext.cs
> +    public static class ServiceDiscoveryEventDescriptionContext
```suggestion
    public static class ServiceDiscoveryEventsContext
```

2021-11-28 10:07 UTC, Jevvry commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/ServiceDiscoveryEventDescription.cs
> +    internal class ServiceDiscoveryEventDescription : IServiceDiscoveryEventDescription
Изначально действительно было что-то похожее. Контекст отдавал [`IServiceDiscoveryEventsBuilder`](https://github.com/vostok/servicediscovery.telemetry/blob/5e9130fca29b713c8c026ca32a433fc51d9450b6/Vostok.ServiceDiscovery.Telemetry/EventBuilder/IServiceDiscoveryEventsBuilder.cs). Но выше есть [комментарий ](https://github.com/vostok/servicediscovery.telemetry/pull/1#discussion_r732774203) и это решили изменить

2021-11-28 10:09 UTC, Jevvry commented on Vostok.ServiceDiscovery.Telemetry/EventDescription/IServiceDiscoveryEventDescription.cs
> +        IReadOnlyList<string> Replicas { get; }
Так получилось как раз из-за того что `ServiceDiscoveryEventsBuilder` отдельный класс и ему нужен доступ к этим свойствам.

2021-12-06 11:54 UTC, KungA requested changes

2021-12-06 11:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventContext/IServiceDiscoveryEventContext.cs
> +    public interface IServiceDiscoveryEventContext
```suggestion
    public interface IServiceDiscoveryEventsContext
```

2021-12-06 11:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventContext/IServiceDiscoveryEventContext.cs
> +namespace Vostok.ServiceDiscovery.Telemetry.EventContext
```suggestion
namespace Vostok.ServiceDiscovery.Telemetry.EventsContext
```

2021-12-06 11:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventContext/IServiceDiscoveryEventContext.cs
> +namespace Vostok.ServiceDiscovery.Telemetry.EventContext
А вообще основные интерфейсы/имплементации лучше вынести в корень.

(ServiceDiscoveryEventContext, IServiceDiscoveryEventContext, ServiceDiscoveryEventContextConfig, ServiceDiscoveryEventContextToken)

2021-12-06 11:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventContext/IServiceDiscoveryEventContext.cs
> +        IReadOnlyList<ServiceDiscoveryEvent> CurrentEvents { get; }
```suggestion
        IEnumerable<ServiceDiscoveryEvent> CurrentEvents { get; }
```

2021-12-06 11:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventContext/IServiceDiscoveryEventContext.cs
> +        /// Sends events from <see cref="CurrentEvents"/> using <see cref="ServiceDiscoveryEventContextConfig.Sender"/>.
And returns?

2021-12-06 11:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventContext/ServiceDiscoveryEventContext.cs
> +            get => FlowingContext.Globals.Get<ServiceDiscoveryEventsBuilder>()?.BuildEvents() ?? new List<ServiceDiscoveryEvent>();
не надо так везде сорить) 

use Array.Empty/Enumerable.Emtpy

2021-12-06 11:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventContext/IServiceDiscoveryEventContext.cs
> +        /// Sends events from <see cref="CurrentEvents"/> using <see cref="ServiceDiscoveryEventContextConfig.Sender"/>.
И как-то не понятно, как использовать этот bool.

Может лучше просто SendFromContext, и писать ошибки в ErrorCallback если чего-то не хватило.

2021-12-06 11:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventContext/ServiceDiscoveryEventContextToken.cs
> +            scope?.Dispose();
а как тут может быть scope = null

2021-12-06 11:54 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry/EventSender/DevNullServiceDiscoveryEventSender.cs
> +namespace Vostok.ServiceDiscovery.Telemetry.EventSender
тут возможно тоже должно быть EventsSender

2021-12-06 12:05 UTC, Jevvry commented on Vostok.ServiceDiscovery.Telemetry/EventContext/IServiceDiscoveryEventContext.cs
> +        /// Sends events from <see cref="CurrentEvents"/> using <see cref="ServiceDiscoveryEventContextConfig.Sender"/>.
И кажется, что пустая коллекция ивентов не является ошибкой.  А ошибки при отправке считается, что sender должен сам обрабатывать,  поэтому кажется, что и ErrorCallback пока не нужен

2021-12-06 14:11 UTC, KungA approved these changes

2021-12-07 05:51 UTC, merged